using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class InstanciarItens : MonoBehaviour
{
    [SerializeField] 
    private GameObject moedaPrefab, relogioPrefab, imaPrefab, lootAmPrefab, lootVPrefab, lootAzPrefab;
    [SerializeField]
    private Transform parent;
    [SerializeField]
    private bool Reta1, Reta2, Reta3, Reta4,Reta5,Reta6,Reta7,Reta8,Reta9,Reta10,Reta11,Reta12,Reta13, Reta14,Reta15,Reta16,Reta17,Reta18,
                    Reta19,Reta20,Reta21,Reta22,Reta23,Reta24,Reta25;
    public static InstanciarItens instanciarItens;
    void Start()
    {
        instanciarItens = this;
    }
    public void LimparObjetos(GameObject modulo){
        Component[] item = modulo.GetComponentsInChildren<Item>();
        for(int i = 0; i < item.Length; i++){
            if(item[i] != null){
                Destroy(item[i].gameObject);
            }
        }
        Component[] loot = modulo.GetComponentsInChildren<LootEncomenda>();
        for(int i = 0; i < loot.Length; i++){
            if(loot[i] != null){
                Destroy(loot[i].gameObject);
            }
        }
    }
    public void Objetos(Transform modulo){  
        if(Reta1){
            GameObject moeda = Instantiate(moedaPrefab);
            Instanciar(moeda, new Vector3(0f, 1f, 12.04f), modulo);
            GameObject moeda1 = Instantiate(moedaPrefab);
            Instanciar(moeda1, new Vector3(0f, 1f, 14.46f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 1f, 16.86f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 1f, 19.87f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 1f, 22.92f),modulo);
            GameObject moeda5 = Instantiate(moedaPrefab);
            Instanciar(moeda5, new Vector3(0f, 1f, 26.53f),modulo);
            GameObject moeda6 = Instantiate(moedaPrefab);
            Instanciar(moeda6, new Vector3(3f, 1f, 31.88f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(3f, 1f, 34.31f),modulo);
        }else if(Reta2){
            GameObject moeda = Instantiate(moedaPrefab);
            Instanciar(moeda, new Vector3(0f, 1f, 4.41f), modulo);
            GameObject moeda1 = Instantiate(moedaPrefab);
            Instanciar(moeda1, new Vector3(0f, 1.47f, 6.07f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 3.05f, 8.15f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 2.04f, 9.64f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 1.4f, 11.04f),modulo);
            GameObject moeda5 = Instantiate(moedaPrefab);
            Instanciar(moeda5, new Vector3(0f, 1f, 12.84f),modulo);
            GameObject lootV = Instantiate(lootVPrefab);
            Instanciar(lootV, new Vector3(3f, 1f, 20.9f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(0f, 1f, 34.85f),modulo);
            GameObject moeda8 = Instantiate(moedaPrefab);
            Instanciar(moeda8, new Vector3(0f, 1f, 36.6f),modulo);
        }else if(Reta3){
            GameObject lootAm = Instantiate(lootAmPrefab);
            Instanciar(lootAm, new Vector3(3f, 1f, 8.28f), modulo);
            GameObject moeda1 = Instantiate(moedaPrefab);
            Instanciar(moeda1, new Vector3(0f, 1f, 9.04f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 1f, 10.49f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 1f, 11.94f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 1f, 13.24f),modulo);
            GameObject moeda5 = Instantiate(moedaPrefab);
            Instanciar(moeda5, new Vector3(0f, 1f, 14.84f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(0f, 1f, 16.11f),modulo);
            GameObject moeda8 = Instantiate(moedaPrefab);
            Instanciar(moeda8, new Vector3(0f, 1f, 17.45f),modulo);
        }else if(Reta4){
            GameObject lootAm = Instantiate(lootAmPrefab);
            Instanciar(lootAm, new Vector3(-3f, 1f, 8.77f), modulo);
            GameObject moeda1 = Instantiate(moedaPrefab);
            Instanciar(moeda1, new Vector3(0f, 1f, 10.76f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 2.08f, 11.95f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 2.73f, 13.64f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 3.2f, 14.89f),modulo);
            GameObject moeda5 = Instantiate(moedaPrefab);
            Instanciar(moeda5, new Vector3(0f, 2.33f, 16.41f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(0f, 1f, 18.26f),modulo);
        }else if(Reta5){
            GameObject moeda1 = Instantiate(moedaPrefab);
            Instanciar(moeda1, new Vector3(0f, 1f, 8.21f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 1f, 9.53f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 1f, 10.94f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 1f, 12.36f),modulo);
            GameObject moeda5 = Instantiate(moedaPrefab);
            Instanciar(moeda5, new Vector3(0f, 1f, 14.13f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(3f, 1f, 26.88f),modulo);
            GameObject moeda8 = Instantiate(moedaPrefab);
            Instanciar(moeda8, new Vector3(3f, 1f, 28.5f),modulo);
            GameObject moeda9 = Instantiate(moedaPrefab);
            Instanciar(moeda9, new Vector3(3f, 1f, 30.04f),modulo);
            GameObject moeda10 = Instantiate(moedaPrefab);
            Instanciar(moeda10, new Vector3(3f, 1f, 31.84f),modulo);
            GameObject moeda11 = Instantiate(moedaPrefab);
            Instanciar(moeda11, new Vector3(3f, 1f, 33.18f),modulo);
        }else if(Reta6){
            GameObject moeda1 = Instantiate(moedaPrefab);
            Instanciar(moeda1, new Vector3(-3f, 1f, 5.06f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(-3f, 1f, 9.44f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(-3f, 1f, 10.84f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(-3f, 1f, 12.05f),modulo);
            GameObject moeda5 = Instantiate(moedaPrefab);
            Instanciar(moeda5, new Vector3(-3f, 1f, 13.31f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(3f, 1f, 23.6f),modulo);
            GameObject moeda8 = Instantiate(moedaPrefab);
            Instanciar(moeda8, new Vector3(3f, 1f, 25.17f),modulo);
            GameObject moeda9 = Instantiate(moedaPrefab);
            Instanciar(moeda9, new Vector3(3f, 1f, 26.36f),modulo);
            GameObject moeda10 = Instantiate(moedaPrefab);
            Instanciar(moeda10, new Vector3(3f, 1f, 29.4f),modulo);
            GameObject moeda11 = Instantiate(moedaPrefab);
            Instanciar(moeda11, new Vector3(3f, 1f, 31.1f),modulo);
            GameObject moeda12 = Instantiate(moedaPrefab);
            Instanciar(moeda12, new Vector3(3f, 1f, 33.27f),modulo);
            GameObject moeda13 = Instantiate(moedaPrefab);
            Instanciar(moeda11, new Vector3(3f, 1f, 35.1f),modulo);
        }else if(Reta7){
            GameObject lootV = Instantiate(lootVPrefab);
            Instanciar(lootV, new Vector3(-3f, 1f, 9.175f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 1f, 11.186f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 1f, 12.99f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 1f, 15.03f),modulo);
            GameObject moeda5 = Instantiate(moedaPrefab);
            Instanciar(moeda5, new Vector3(0f, 1f, 17.12f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(3f, 1f, 22.7f),modulo);
            GameObject moeda8 = Instantiate(moedaPrefab);
            Instanciar(moeda8, new Vector3(3f, 1f, 24.51f),modulo);
            GameObject moeda9 = Instantiate(moedaPrefab);
            Instanciar(moeda9, new Vector3(3f, 1.78f, 27.43f),modulo);
            GameObject moeda10 = Instantiate(moedaPrefab);
            Instanciar(moeda10, new Vector3(3f, 2.85f, 29.56f),modulo);
            GameObject moeda11 = Instantiate(moedaPrefab);
            Instanciar(moeda11, new Vector3(3f, 3.68f, 30.86f),modulo);
            GameObject moeda12 = Instantiate(moedaPrefab);
            Instanciar(moeda12, new Vector3(3f, 2.82f, 32.34f),modulo);
            GameObject moeda13 = Instantiate(moedaPrefab);
            Instanciar(moeda11, new Vector3(3f, 1.35f, 34.19f),modulo);
        }else if(Reta8){
            GameObject moeda1 = Instantiate(moedaPrefab);
            Instanciar(moeda1, new Vector3(0f, 1f, 11.47f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 1f, 12.7f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 1f, 14.24f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 1f, 15.72f),modulo);
            GameObject lootAz = Instantiate(lootAzPrefab);
            Instanciar(lootAz, new Vector3(0f, 1f, 29.88f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(3f, 1f, 34.43f),modulo);
            GameObject moeda8 = Instantiate(moedaPrefab);
            Instanciar(moeda8, new Vector3(3f, 1f, 36.23f),modulo);
            GameObject moeda9 = Instantiate(moedaPrefab);
            Instanciar(moeda9, new Vector3(3f, 1f, 37.96f),modulo);
            GameObject moeda10 = Instantiate(moedaPrefab);
            Instanciar(moeda10, new Vector3(3f, 1f, 39.7f),modulo);
        }else if(Reta9){
            GameObject moeda1 = Instantiate(moedaPrefab);
            Instanciar(moeda1, new Vector3(0f, 1f, 8.21f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 1f, 10.34f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 1f, 12.47f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 1f, 14.86f),modulo);
            GameObject ima = Instantiate(imaPrefab);
            Instanciar(ima, new Vector3(3f, 1f, 13.62f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(-3f, 1f, 28.03f),modulo);
            GameObject moeda8 = Instantiate(moedaPrefab);
            Instanciar(moeda8, new Vector3(-3f, 1f, 29.5f),modulo);
            GameObject moeda9 = Instantiate(moedaPrefab);
            Instanciar(moeda9, new Vector3(-3f, 1f, 31.32f),modulo);
            GameObject moeda10 = Instantiate(moedaPrefab);
            Instanciar(moeda10, new Vector3(-3f, 1f, 32.92f),modulo);
            GameObject moeda11 = Instantiate(moedaPrefab);
            Instanciar(moeda11, new Vector3(-3f, 1f, 34.52f),modulo);
        }else if(Reta10){
            GameObject lootV = Instantiate(lootVPrefab);
            Instanciar(lootV, new Vector3(-3f, 1f, 19.039f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 1f, 20.3f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 2.56f, 21.35f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 2.92f, 22.81f),modulo);
            GameObject ima = Instantiate(imaPrefab);
            Instanciar(ima, new Vector3(0f, 1.58f, 24.53f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(0f, 1f, 26.08f),modulo);
            GameObject moeda8 = Instantiate(moedaPrefab);
            Instanciar(moeda8, new Vector3(3f, 1f, 27.56f),modulo);
            GameObject moeda9 = Instantiate(moedaPrefab);
            Instanciar(moeda9, new Vector3(3f, 1f, 29.5f),modulo);
            GameObject moeda10 = Instantiate(moedaPrefab);
            Instanciar(moeda10, new Vector3(3f, 1f, 31.23f),modulo);
        }else if(Reta11){
            GameObject relogio = Instantiate(relogioPrefab);
            Instanciar(relogio, new Vector3(-3f, 1f, 6.73f), modulo);
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 1f, 7.5f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 1f, 9.62f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 1f, 12.35f),modulo);
            GameObject ima = Instantiate(imaPrefab);
            Instanciar(ima, new Vector3(0f, 1f, 14.78f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(0f, 1f, 17.14f),modulo);
            GameObject lootAz = Instantiate(lootAzPrefab);
            Instanciar(lootAz, new Vector3(-3f, 1f, 17.4f),modulo);
            GameObject moeda9 = Instantiate(moedaPrefab);
            Instanciar(moeda9, new Vector3(3f, 1f, 28.68f),modulo);
            GameObject moeda10 = Instantiate(moedaPrefab);
            Instanciar(moeda10, new Vector3(3f, 1f, 31.09f),modulo);
            GameObject moeda11 = Instantiate(moedaPrefab);
            Instanciar(moeda11, new Vector3(3f, 1f, 34.17f),modulo);
            GameObject moeda12 = Instantiate(moedaPrefab);
            Instanciar(moeda12, new Vector3(3f, 1f, 37.15f),modulo);
            GameObject moeda13 = Instantiate(moedaPrefab);
            Instanciar(moeda13, new Vector3(3f, 1f, 38.87f),modulo);
        }else if(Reta12){
            GameObject moeda2 = Instantiate(moedaPrefab);
            Instanciar(moeda2, new Vector3(0f, 1f, 6.82f),modulo);
            GameObject moeda3 = Instantiate(moedaPrefab);
            Instanciar(moeda3, new Vector3(0f, 1f, 8.58f),modulo);
            GameObject moeda4 = Instantiate(moedaPrefab);
            Instanciar(moeda4, new Vector3(0f, 1f, 10.38f),modulo);
            GameObject moeda5 = Instantiate(moedaPrefab);
            Instanciar(moeda5, new Vector3(0f, 1f, 12.17f),modulo);
            GameObject moeda7 = Instantiate(moedaPrefab);
            Instanciar(moeda7, new Vector3(0f, 1f, 14.23f),modulo);
            GameObject lootV = Instantiate(lootVPrefab);
            Instanciar(lootV, new Vector3(-3f, 2.74f, 23.28f),modulo);
            GameObject moeda9 = Instantiate(moedaPrefab);
            Instanciar(moeda9, new Vector3(-3f, 1f, 25.84f),modulo);
            GameObject moeda10 = Instantiate(moedaPrefab);
            Instanciar(moeda10, new Vector3(-3f, 1f, 28.79f),modulo);
            GameObject moeda11 = Instantiate(moedaPrefab);
            Instanciar(moeda11, new Vector3(-3f, 1f, 30.27f),modulo);
            GameObject moeda12 = Instantiate(moedaPrefab);
            Instanciar(moeda12, new Vector3(-3f, 1f, 31.42f),modulo);
        }else if(Reta13){
        GameObject lootAm = Instantiate(lootAmPrefab);
        Instanciar(lootAm, new Vector3(0f, 1f, 3.1f),modulo);
        GameObject moeda3 = Instantiate(moedaPrefab);
        Instanciar(moeda3, new Vector3(0f, 1f, 5.99f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(0f, 1f, 7.21f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(0f, 1f, 8.42f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(0f, 1f, 9.58f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(0f, 1f, 10.76f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(-3f, 1f, 25.9f),modulo);
        GameObject moeda10 = Instantiate(moedaPrefab);
        Instanciar(moeda10, new Vector3(-3f, 1f, 27.3f),modulo);
        GameObject moeda11 = Instantiate(moedaPrefab);
        Instanciar(moeda11, new Vector3(-3f, 1f, 29.26f),modulo);
        GameObject moeda12 = Instantiate(moedaPrefab);
        Instanciar(moeda12, new Vector3(-3f, 1f, 30.59f),modulo);
        }else if(Reta14){
        GameObject moeda1 = Instantiate(moedaPrefab);
        Instanciar(moeda1, new Vector3(0f, 1f, 6.4f),modulo);
        GameObject moeda3 = Instantiate(moedaPrefab);
        Instanciar(moeda3, new Vector3(0f, 1f, 7.15f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(0f, 1f, 8.43f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(0f, 1f, 9.64f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(0f, 1f, 10.73f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(3f, 2.8f, 27.27f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(3f, 4.6f, 29.33f),modulo);
        GameObject moeda10 = Instantiate(moedaPrefab);
        Instanciar(moeda10, new Vector3(3f, 1f, 30.7f),modulo);
        GameObject moeda11 = Instantiate(moedaPrefab);
        Instanciar(moeda11, new Vector3(3f, 1f, 32.55f),modulo);
        GameObject lootV = Instantiate(lootVPrefab);
        Instanciar(lootV, new Vector3(0f, 1f, 33.32f),modulo);
        }else if(Reta15){
        GameObject lootAz = Instantiate(lootAzPrefab);
        Instanciar(lootAz, new Vector3(-3f, 1f, 4.09f),modulo);
        GameObject ima = Instantiate(imaPrefab);
        Instanciar(ima, new Vector3(3f, 1f, 14.26f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(0f, 1f, 17.97f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(0f, 2.03f, 20.81f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(0f, 3.59f, 22.18f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(0f, 2.5f, 23.5f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(0f, 1f, 25.12f),modulo);
        GameObject moeda10 = Instantiate(moedaPrefab);
        Instanciar(moeda10, new Vector3(-3f, 1f, 29.61f),modulo);
        GameObject moeda11 = Instantiate(moedaPrefab);
        Instanciar(moeda11, new Vector3(-3f, 1f, 31.33f),modulo);
        GameObject moeda12 = Instantiate(moedaPrefab);
        Instanciar(moeda12, new Vector3(-3f, 1f, 33.57f),modulo);
        GameObject moeda13 = Instantiate(moedaPrefab);
        Instanciar(moeda13, new Vector3(-3f, 1f, 35.42f),modulo);
        }else if(Reta16){
        GameObject moeda1 = Instantiate(moedaPrefab);
        Instanciar(moeda1, new Vector3(3f, 1f, 6.21f),modulo);
        GameObject moeda2 = Instantiate(moedaPrefab);
        Instanciar(moeda2, new Vector3(3f, 1f, 7.4f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(3f, 1f, 8.76f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(3f, 1f, 10.19f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(3f, 1f, 11.68f),modulo);
        GameObject lootV = Instantiate(lootVPrefab);
        Instanciar(lootV, new Vector3(3f, 1f, 26.71f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(-3f, 1f, 32.19f),modulo);
        GameObject moeda10 = Instantiate(moedaPrefab);
        Instanciar(moeda10, new Vector3(-3f, 1f, 33.81f),modulo);
        GameObject moeda11 = Instantiate(moedaPrefab);
        Instanciar(moeda11, new Vector3(-3f, 1f, 35.23f),modulo);
        GameObject moeda12 = Instantiate(moedaPrefab);
        Instanciar(moeda12, new Vector3(-3f, 1f,36.54f),modulo);
        }else if(Reta17){
        GameObject moeda1 = Instantiate(moedaPrefab);
        Instanciar(moeda1, new Vector3(-3f, 1f, 11.211f),modulo);
        GameObject moeda2 = Instantiate(moedaPrefab);
        Instanciar(moeda2, new Vector3(-3f, 2.214f, 12.9f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(-3f, 3.53f, 14.44f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(-3f, 3.09f, 15.65f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(-3f, 1.67f, 16.63f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(-3f, 1f, 18.22f),modulo);
        GameObject lootAm = Instantiate(lootAmPrefab);
        Instanciar(lootAm, new Vector3(0f, 1f, 28.44f),modulo);
        GameObject moeda10 = Instantiate(moedaPrefab);
        Instanciar(moeda10, new Vector3(0f, 1f, 30.171f),modulo);
        GameObject moeda11 = Instantiate(moedaPrefab);
        Instanciar(moeda11, new Vector3(0f, 1f, 31.92f),modulo);
        GameObject moeda12 = Instantiate(moedaPrefab);
        Instanciar(moeda12, new Vector3(0f, 1f, 33.8f),modulo);
         GameObject ima = Instantiate(imaPrefab);
        Instanciar(ima, new Vector3(3f, 4f, 13.82f),modulo);
        }else if(Reta18){
        GameObject moeda1 = Instantiate(moedaPrefab);
        Instanciar(moeda1, new Vector3(-3f, 1f, 10.48f),modulo);
        GameObject moeda2 = Instantiate(moedaPrefab);
        Instanciar(moeda2, new Vector3(-3f, 1f, 11.76f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(-3f, 1f, 13.68f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(-3f, 1f, 15.99f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(-3f, 1f, 17.67f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(0f, 1f, 30.27f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(0f, 1f, 32.2f),modulo);
        GameObject moeda10 = Instantiate(moedaPrefab);
        Instanciar(moeda10, new Vector3(0f, 1f, 34.35f),modulo);
        GameObject moeda11 = Instantiate(moedaPrefab);
        Instanciar(moeda11, new Vector3(0f, 1f, 36.16f),modulo);
        GameObject lootAz = Instantiate(lootAzPrefab);
        Instanciar(lootAz, new Vector3(3f, 1f, 36.13f),modulo);
        }else if(Reta19){
        GameObject relogio = Instantiate(relogioPrefab);
        Instanciar(relogio, new Vector3(-3f, 2.654f, 15.34f),modulo);
        GameObject moeda2 = Instantiate(moedaPrefab);
        Instanciar(moeda2, new Vector3(0f, 1f, 14.25f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(0f, 1f, 15.4f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(0f, 1f, 16.75f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(0f, 1f, 18.03f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(0f, 1f, 19.7f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(-3f, 1f, 19.41f),modulo);
        }else if(Reta20){
        GameObject moeda1 = Instantiate(moedaPrefab);
        Instanciar(moeda1, new Vector3(-3f, 1f, 20.53f),modulo);
        GameObject moeda2 = Instantiate(moedaPrefab);
        Instanciar(moeda2, new Vector3(-3f, 1f, 22.89f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(-3f, 1f, 25.22f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(0f, 1f, 29.23f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(0f, 1f, 30.49f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(0f, 1f, 32.22f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(0f, 1f, 34.03f),modulo);
        }else if(Reta21){
        GameObject lootV = Instantiate(lootVPrefab);
        Instanciar(lootV, new Vector3(0f, 1f, 5.523f),modulo);
        GameObject moeda2 = Instantiate(moedaPrefab);
        Instanciar(moeda2, new Vector3(3f, 1f, 7.63f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(3f, 1f, 9.86f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(3f, 1f, 11.99f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(3f, 1f, 13.35f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(3f, 1f, 14.97f),modulo);
        GameObject lootAz = Instantiate(lootAzPrefab);
        Instanciar(lootAz, new Vector3(3f, 4f, 19.89f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(0f, 1f, 19.45f),modulo);
        GameObject moeda10 = Instantiate(moedaPrefab);
        Instanciar(moeda10, new Vector3(0f, 1f, 21.85f),modulo);
        GameObject moeda11 = Instantiate(moedaPrefab);
        Instanciar(moeda11, new Vector3(0f, 1f, 24.48f),modulo);
        GameObject moeda12 = Instantiate(moedaPrefab);
        Instanciar(moeda12, new Vector3(0f, 1f, 26.13f),modulo);
        GameObject moeda13 = Instantiate(moedaPrefab);
        Instanciar(moeda13, new Vector3(0f, 1f, 28.93f),modulo);
        GameObject moeda14 = Instantiate(moedaPrefab);
        Instanciar(moeda14, new Vector3(0f, 1f, 30.7f),modulo);
        }else if(Reta22){
        GameObject relogio = Instantiate(relogioPrefab);
        Instanciar(relogio, new Vector3(-3f, 1f, 4.79f),modulo);
        GameObject moeda2 = Instantiate(moedaPrefab);
        Instanciar(moeda2, new Vector3(3f, 1f, 12.906f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(3f, 1f, 14.3f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(3f, 1f, 15.91f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(3f, 1f, 17.4f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(-3f, 1f, 18.18f),modulo);
        GameObject moeda1 = Instantiate(moedaPrefab);
        Instanciar(moeda1, new Vector3(-3f, 1f, 19.67f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(-3f, 1f, 21.11f),modulo);
        GameObject lootAm = Instantiate(lootAmPrefab);
        Instanciar(lootAm, new Vector3(0f, 1f, 34.98f),modulo);
        }else if(Reta23){
        GameObject ima = Instantiate(imaPrefab);
        Instanciar(ima, new Vector3(-3f, 1f, 18.79f),modulo);
        GameObject moeda2 = Instantiate(moedaPrefab);
        Instanciar(moeda2, new Vector3(3f, 1f, 14.89f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(3f, 1f, 17.06f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(3f, 1f, 19.56f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(3f, 1f, 21.53f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(-3f, 1f, 27.42f),modulo);
        GameObject moeda1 = Instantiate(moedaPrefab);
        Instanciar(moeda1, new Vector3(-3f, 1f, 29.7f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(-3f, 1f, 31.98f),modulo);
        GameObject moeda10 = Instantiate(moedaPrefab);
        Instanciar(moeda10, new Vector3(0f, 1f, 33.53f),modulo);
        GameObject moeda11 = Instantiate(moedaPrefab);
        Instanciar(moeda11, new Vector3(0f, 1f, 35.38f),modulo);
        }else if(Reta24){
        GameObject lootAm = Instantiate(lootAmPrefab);
        Instanciar(lootAm, new Vector3(-3f, 1f, 18.38f),modulo);
        GameObject moeda2 = Instantiate(moedaPrefab);
        Instanciar(moeda2, new Vector3(3f, 1f, 17.262f),modulo);
        GameObject moeda4 = Instantiate(moedaPrefab);
        Instanciar(moeda4, new Vector3(3f, 2.44f, 18.25f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(3f, 3.35f, 19.66f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(3f, 3.35f, 20.95f),modulo);
        GameObject moeda8 = Instantiate(moedaPrefab);
        Instanciar(moeda8, new Vector3(3f, 1f, 22.53f),modulo);
        GameObject moeda1 = Instantiate(moedaPrefab);
        Instanciar(moeda1, new Vector3(3f, 1f, 24.18f),modulo);
        GameObject moeda9 = Instantiate(moedaPrefab);
        Instanciar(moeda9, new Vector3(-3f, 1f, 22.62f),modulo);
        GameObject moeda10 = Instantiate(moedaPrefab);
        Instanciar(moeda10, new Vector3(-3f, 1f, 24.29f),modulo);
        GameObject moeda11 = Instantiate(moedaPrefab);
        Instanciar(moeda11, new Vector3(-3f, 1f, 26.62f),modulo);
        GameObject moeda12 = Instantiate(moedaPrefab);
        Instanciar(moeda12, new Vector3(-3f, 1f, 28.47f),modulo);
        }else if(Reta25){
        GameObject moeda3 = Instantiate(moedaPrefab);
        Instanciar(moeda3, new Vector3(0f, 1f, 11.97f),modulo);
        GameObject moeda2 = Instantiate(moedaPrefab);
        Instanciar(moeda2, new Vector3(0f, 1f, 17.86f),modulo);
        GameObject lootAz = Instantiate(lootAzPrefab);
        Instanciar(lootAz, new Vector3(0f, 1f, 22.475f),modulo);
        GameObject moeda5 = Instantiate(moedaPrefab);
        Instanciar(moeda5, new Vector3(0f, 1f, 27.09f),modulo);
        GameObject moeda7 = Instantiate(moedaPrefab);
        Instanciar(moeda7, new Vector3(0f, 1f, 31.92f),modulo);
        }
    }
    void Instanciar(GameObject objeto, Vector3 pos, Transform modulo){
        objeto.transform.parent = modulo;
        objeto.transform.localPosition = pos;
    }
}
